name = "Countries"
uuid = "5bf49175-83fb-4b6d-82b5-d6ded85154ae"
version = "0.3.2"
authors = ["Christopher Doris <github.com/cjdoris>"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
ReadOnlyArrays = "988b38a3-91fc-5605-94a2-ee2116b3bd83"
iso_codes_jll = "bf975903-5238-5d20-8243-bc370bc1e7e5"

[compat]
JSON = "1.4"
ReadOnlyArrays = "0.1.1, 0.2"
iso_codes_jll = "4.0"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
